# Generated by Django 3.2.11 on 2022-01-16 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220112_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 10, 7, 19, 303042, tzinfo=utc), verbose_name='Срок активации'),
        ),
    ]
