# Generated by Django 3.2.11 on 2022-01-19 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20220116_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 19, 26, 50, 631915, tzinfo=utc), verbose_name='Срок активации'),
        ),
    ]
